version: '3'

volumes:
  coinmarket_crawler_local_postgres_data: {}
  coinmarket_crawler_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: coinmarket_crawler_local_django
    container_name: coinmarket_crawler_local_django
    depends_on:
      - postgres
      #- mailhog
    volumes:
      - .:/app:z
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: /start

  celeryworker:
    <<: *django
    image: coinmarket_crawler_local_celeryworker
    container_name: coinmarket_crawler_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: coinmarket_crawler_local_celerybeat
    container_name: coinmarket_crawler_local_celerybeat
    depends_on:
      - redis
      - postgres
      #- mailhog
      - django
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: coinmarket_crawler_local_flower
    container_name: coinmarket_crawler_local_flower
    ports:
      - "5555:5555"
    command: /start-flower

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: coinmarket_crawler_local_postgres
    container_name: coinmarket_crawler_local_postgres
    volumes:
      - coinmarket_crawler_local_postgres_data:/var/lib/postgresql/data
      - coinmarket_crawler_local_postgres_data_backups:/backups
    env_file:
      - ./.env

  redis:
    image: redis:6
    container_name: coinmarket_crawler_local_redis

  adminer:
    image: adminer:4
    restart: always
    container_name: coinmarket_crawler_local_adminer
    depends_on:
      - postgres
    ports:
      - 8181:8080

  dozzle:
    image: amir20/dozzle:latest
    container_name: coinmarket_crawler_local_dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080
    environment:
      DOZZLE_LEVEL: trace
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
