# Generated by Django 4.0.9 on 2023-02-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=250)),
                ('logo', models.URLField()),
                ('symbol', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('price_change', models.CharField(max_length=100)),
                ('price_low_high', models.CharField(max_length=500)),
                ('trading_volume', models.CharField(max_length=500)),
                ('volume_market_cap', models.DecimalField(decimal_places=5, max_digits=15)),
                ('fully_diluted_market_cap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('market_dominance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('market_rank', models.CharField(max_length=5)),
                ('circulating_supply', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_supply', models.DecimalField(decimal_places=2, max_digits=15)),
                ('max_supply', models.DecimalField(decimal_places=2, max_digits=15)),
                ('html_raw', models.TextField(blank=True)),
                ('cryptocurrency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coinmarket.cryptocurrency')),
            ],
        ),
    ]
