# Generated by Django 4.0.9 on 2023-02-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarket', '0002_alter_cryptocurrency_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
