# Generated by Django 4.0.9 on 2023-02-27 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarket', '0004_alter_cryptocurrency_name_alter_cryptocurrency_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='fully_diluted_market_cap',
        ),
    ]
