# Generated by Django 4.0.9 on 2023-02-27 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinmarket', '0005_remove_rate_fully_diluted_market_cap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='html_raw',
        ),
    ]
